title: "Benjamin A. Petersen | UX Developer in Raleigh, NC"
description: ""
url: "http://benjaminapetersen.me"
twitter: bapetersen
github:  benjaminapetersen
linkedin: benjaminapetersen
permalink: /:title/
baseurl: ""
timezone: America/New_York
kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
